# permissions for end users to view staticpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: staticpod-viewer-role
rules:
- apiGroups:
  - sp-yduck.com
  resources:
  - staticpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sp-yduck.com
  resources:
  - staticpods/status
  verbs:
  - get
