apiVersion: sp-yduck.com/v1alpha1
kind: StaticPod
metadata:
  name: staticpod-nginx
  namespace: staticpod-system
spec:
  template: 
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: web
              containerPort: 80
              protocol: TCP